import { Issue } from './types';

// Mock data to simulate backend response
export const initialIssues: Issue[] = [
    {
        id: 1,
        title: "Massive Pothole on Main St",
        description: "A very deep pothole that is causing damage to cars. Needs immediate attention.",
        category: "Roads",
        image_url: "/pothole.png",
        latitude: 37.7858,
        longitude: -122.4064,
        priority: "CRITICAL",
        status: "REPORTED",
        trust_score: 0.95,
        is_verified: true,
        user_id: "urban_explorer",
        upvotes: 42,
        comment_count: 2,
        created_at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    },
    {
        id: 2,
        title: "Illegal Garbage Dumping",
        description: "Large pile of construction waste left on the sidewalk for 3 days.",
        category: "Garbage",
        image_url: "/garbage.png",
        latitude: 37.7749,
        longitude: -122.4194,
        priority: "HIGH",
        status: "VERIFIED",
        trust_score: 0.88,
        is_verified: true,
        user_id: "clean_city_fan",
        upvotes: 28,
        comment_count: 0,
        created_at: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    },
    {
        id: 3,
        title: "Broken Water Main",
        description: "Water gushing out from the pavement. Wasting a lot of water.",
        category: "Water",
        image_url: "/water_main.png",
        latitude: 37.7649,
        longitude: -122.4294,
        priority: "CRITICAL",
        status: "IN_PROGRESS",
        trust_score: 0.98,
        is_verified: true,
        user_id: "water_watcher",
        upvotes: 56,
        comment_count: 1,
        created_at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    },
    {
        id: 4,
        title: "Street Light Out",
        description: "The entire block is dark at night. Safety concern for pedestrians.",
        category: "Safety",
        image_url: "/street_light.png",
        latitude: 37.7949,
        longitude: -122.3994,
        priority: "MEDIUM",
        status: "REPORTED",
        trust_score: 0.75,
        is_verified: false,
        user_id: "night_walker",
        upvotes: 12,
        comment_count: 0,
        created_at: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    }
];
